# These are supported funding model platforms

custom: "https://paypal.me/huizebruin"
custom: "https://www.paypal.com/donate/?hosted_button_id=E5MLX3AC2FZUQ"
custom: "https://www.buymeacoffee.com/Huizebruin"