---
# Build the ESPHome binary firmware
# And deploy it to Github Pages.
name: Publish firmware pull request

on:
  pull_request:
# on:
#   workflow_dispatch:
#   release:
#     types:
#       - published

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - esphome/pulscounter.yaml
          - esphome/watermeter.yaml
          - esphome/S0-puls-kwh-puls.yaml
          - esphome/S0-puls-DSZ12D.yaml
          - esphome/S0-puls-LEM022SJ.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v1.5.2
        with:
          yaml_file: ${{ matrix.file }}