---
# Build the ESPHome binary firmware
# And deploy it to Github Pages.
name: Publish firmware

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    name: "🛠️ ESPHome firmware"
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: https://github.com/huizebruin/s0tool/blob/fea1747bb55551a155032a6106443f715ec011f4/esphome/pulscounter.yaml
      name: S0tool
